### ISSUE TITLE
Update very.badssl.com doge to reference CBC instead of RC4

### ISSUE THREAD

**Issue by lgarron** [chromium/badssl.com#104]
Followup to #96.

Source in Pixelmator format is on the `assets` branch:
https://github.com/lgarron/badssl.com/tree/assets/very.badssl.com

**Comment by marumari** [comment]
If you wanted to export the original in a more portable format (PSD?), I'd be happy to update it.  I have both Photoshop and Affinity Photo (which is >>> Pixelmator, imo)
