### ISSUE TITLE
no-san.badssl.com

### ISSUE THREAD

**Issue by lgarron** [chromium/badssl.com#193]
I don't think we have this one yet.

Per the Baseline Requirements, every cert needs a SAN. But it used to be common to just put the host in the common name. (Someone correct me if I'm wrong on either count.)

**Comment by marumari** [comment]
Pretty sure that's exactly correct.

**Comment by lgarron** [comment]
😳
<img width="1045" alt="screen shot 2016-08-09 at 13 39 42" src="https://cloud.githubusercontent.com/assets/248078/17533321/0652b6ee-5e39-11e6-9e82-fc71870ee488.png">
😰
![screen shot 2016-08-09 at 13 39 50](https://cloud.githubusercontent.com/assets/248078/17533322/0657834a-5e39-11e6-8bb8-2b169f2055e8.png)

**Comment by marumari** [comment]
Seeing them side-by-side, I think our red pages need nervous face emoji.

**Comment by lgarron** [comment]
> Seeing them side-by-side, I think our red pages need nervous face emoji.

I've been thinking of how to limit the use of color on the front page without losing the distinctiveness. Perhaps emoji are just what we need?
