### ISSUE TITLE
Subdomain with ERR_CERTIFICATE_TRANSPARENCY_REQUIRED

### ISSUE THREAD

**Issue by konklone** [chromium/badssl.com#215]
It'd be great to have a reliable endpoint for demonstrating and testing `NET::ERR_CERTIFICATE_TRANSPARENCY_REQUIRED` errors, like this one:

![error](https://cloud.githubusercontent.com/assets/4592/19323930/0cf6c3e2-908d-11e6-984b-cb7b3f2e5ada.png)

It can be an ordinary DV certificate, and hopefully shouldn't be too expensive -- perhaps Symantec would even donate one. I'm not sure if there's any meaningful difference in having an endpoint with SCTs for non-compliant-ly redacted certs (like the above example) or for an endpoint with no SCTs at all. Whatever's easier.

**Comment by lgarron** [comment]
By "endpoint" I presume you mean "subdomain", not "API path"?

I'd be happy to add one if we can get a cert.

**Comment by konklone** [comment]
Yep, subdomain. Thanks for considering it!

**Comment by AGWA** [comment]
I can donate a Symantec certificate with an invalid embedded SCT (for a redacted pre-cert) that will trigger this error.  I just need a CSR and an email address which can be used for DCV.

**Comment by lgarron** [comment]
I can generate a CSR.
How does `missing-sct.badssl.com` sound?

**Comment by AGWA** [comment]
I suggest `invalid-sct.badssl.com`, since there will be an SCT, but it will be invalid.  You might want to keep `missing-sct.badssl.com` available for future use once CT becomes mandatory.

**Comment by lgarron** [comment]
Ah, I scanned your previous message too quickly. `invalid-sct` it is.

**Comment by lgarron** [comment]
Actually, the main point is to have an invalid SCT where a valid one is expected. `invalid-expected-sct`?

**Comment by AGWA** [comment]
Yeah, `invalid-expected-sct` is even better.

**Comment by lgarron** [comment]
-----BEGIN CERTIFICATE REQUEST-----
    MIIDAjCCAeoCAQAwdTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWEx
    FjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDzANBgNVBAoMBkJhZFNTTDEoMCYGA1UE
    AwwfaW52YWxpZC1leHBlY3RlZC1zY3QuYmFkc3NsLmNvbTCCASIwDQYJKoZIhvcN
    AQEBBQADggEPADCCAQoCggEBAMIE7PiM7gTCs9hQ1XBYzJMY61yoaEmwIrX5lZ6x
    Kyx2PmzAS2BMTOqytMAPgLaw+XLJhgL5XEFdEyt/ccRLvOmULlA3pmccYYz2QULF
    RtMWhyefdOsKnRFSJiFzbIRMeVXk0WvoBj1IFVKtsyjbqv9u/2CVSndrOfEk0TG2
    3U3AxPxTuW1CrbV8/q71FdIzSOciccfCFHpsKOo3St/qbLVytH5aohbcabFXRNsK
    Eqveww9HdFxBIuGa+RuT5q0iBikusbpJHAwnnqP7i/dAcgCskgjZjFeEU4EFy+b+
    a1SYQCeFxxC7c3DvaRhBB0VVfPlkPz0sw6l865MaTIbRyoUCAwEAAaBIMEYGCSqG
    SIb3DQEJDjE5MDcwCQYDVR0TBAIwADAqBgNVHREEIzAhgh9pbnZhbGlkLWV4cGVj
    dGVkLXNjdC5iYWRzc2wuY29tMA0GCSqGSIb3DQEBBQUAA4IBAQCKaXtokN0Bbrt1
    ahbBzfmY9c8Cd5sv0M4Q9lbfmQN6/XlCtg0orMJU1XjkTxvD9/EQBJ7rSc1CflyK
    wq9IKRoMqwjuw8tzXuDkqNyDmIk/GQmKMLdddaJrLQpB5I0cqL0Cbd6Xu+tErlwv
    Tdi5ZOz9S1nyMyVH5wCbiaNSYdmYspPIwxOtD3WqokYyXQ9b6WwzP1X0F7+9ZhIo
    MpvC9nhPEd147nNjsA4aA2eq2kC+7/vTGpuVURU6WW8Q6qCkSVZdEUDdWXTw5YfE
    +ffioDDabbggT4cvuT/0v541F5E0YiWl3LucCtObi3HG4naVpqdDlE0NpfJTD+Y2
    ivW5ZM9z
    -----END CERTIFICATE REQUEST-----

**Comment by AGWA** [comment]
Which of `{admin,administrator,hostmaster,postmaster,webmaster}@badssl.com` will reach you?

**Comment by lgarron** [comment]
Possibly any, but `postmaster` is explicitly forwarded to me.

**Comment by AGWA** [comment]
An approval emails is being sent to `postmaster`, and another will follow soon after.  Please approve both.  (Currently, I have to issue a non-redacted cert first and then request a reissue that's redacted.)

**Comment by lgarron** [comment]
I have a verification request for RapidSSL order ID 14396307; is that correct?

**Comment by AGWA** [comment]
Correct.

**Comment by lgarron** [comment]
Approved the first request.

**Comment by lgarron** [comment]
Approved second request (same order ID).

**Comment by AGWA** [comment]
Certificate chain:

```
-----BEGIN CERTIFICATE-----
MIIFGDCCBACgAwIBAgIQGkTSlT8/2bAURo/J1C2/STANBgkqhkiG9w0BAQsFADBC
MQswCQYDVQQGEwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMS
UmFwaWRTU0wgU0hBMjU2IENBMB4XDTE2MTExNzAwMDAwMFoXDTE4MTExNzIzNTk1
OVowKjEoMCYGA1UEAwwfaW52YWxpZC1leHBlY3RlZC1zY3QuYmFkc3NsLmNvbTCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMIE7PiM7gTCs9hQ1XBYzJMY
61yoaEmwIrX5lZ6xKyx2PmzAS2BMTOqytMAPgLaw+XLJhgL5XEFdEyt/ccRLvOmU
LlA3pmccYYz2QULFRtMWhyefdOsKnRFSJiFzbIRMeVXk0WvoBj1IFVKtsyjbqv9u
/2CVSndrOfEk0TG23U3AxPxTuW1CrbV8/q71FdIzSOciccfCFHpsKOo3St/qbLVy
tH5aohbcabFXRNsKEqveww9HdFxBIuGa+RuT5q0iBikusbpJHAwnnqP7i/dAcgCs
kgjZjFeEU4EFy+b+a1SYQCeFxxC7c3DvaRhBB0VVfPlkPz0sw6l865MaTIbRyoUC
AwEAAaOCAiAwggIcMCoGA1UdEQQjMCGCH2ludmFsaWQtZXhwZWN0ZWQtc2N0LmJh
ZHNzbC5jb20wCQYDVR0TBAIwADArBgNVHR8EJDAiMCCgHqAchhpodHRwOi8vZ3Au
c3ltY2IuY29tL2dwLmNybDBvBgNVHSAEaDBmMGQGBmeBDAECATBaMCoGCCsGAQUF
BwIBFh5odHRwczovL3d3dy5yYXBpZHNzbC5jb20vbGVnYWwwLAYIKwYBBQUHAgIw
IAweaHR0cHM6Ly93d3cucmFwaWRzc2wuY29tL2xlZ2FsMB8GA1UdIwQYMBaAFJfC
J1CewsnsDIgyyHyt4qYBT9pvMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr
BgEFBQcDAQYIKwYBBQUHAwIwVwYIKwYBBQUHAQEESzBJMB8GCCsGAQUFBzABhhNo
dHRwOi8vZ3Auc3ltY2QuY29tMCYGCCsGAQUFBzAChhpodHRwOi8vZ3Auc3ltY2Iu
Y29tL2dwLmNydDAPBgMrZU0ECDAGAgEBAgEBMIGKBgorBgEEAdZ5AgQCBHwEegB4
AHYAp85KTmIH4K3e5f2qSx+GdodntdACpV1HMQ5+ZwqV6rIAAAFYb//OtAAABAMA
RzBFAiEAuAOtNPb8Dyz/hKCG5dfPWvAKB2Jqf7OmRGTxlaRIRRECIC9hjVMbb0q4
CmeyB+GPba3RBEpes4nvfGDCaFP5PR9tMA0GCSqGSIb3DQEBCwUAA4IBAQBIMHww
vuW8XOBdxw0Mq0z3NFsAW2XvkcXtTGmB5savCpRJ6LN0ub6NJX+KiFmDo9voMDro
YL7o9i+BrSAFo3hr8QNxLLJaXD54h8lJ0oCkzyZtzezM8p2PWsEjouePtdE0AIHn
RK0SnKBk9w0b3CMSbzObc1Cu8ATqZnE51d7xurim7qTZMhJM2hi9HeLPLVdEBiuC
zmYtNpRMMQqbQvvrXftAohq/W90rK42Ss8kYIf8FsVTa5VaqXW7lIh/3JmBNLZ1D
Aw5rmaztWlYO64YS7z4am5d9h2rrF1rfgv9Mc3caxAUO3sJZDRyhYaj+7BUgv8HR
otJHkjr2ASPp31Yf
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIETTCCAzWgAwIBAgIDAjpxMA0GCSqGSIb3DQEBCwUAMEIxCzAJBgNVBAYTAlVTMRYwFAYDVQQK
Ew1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9iYWwgQ0EwHhcNMTMxMjExMjM0
NTUxWhcNMjIwNTIwMjM0NTUxWjBCMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5j
LjEbMBkGA1UEAxMSUmFwaWRTU0wgU0hBMjU2IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAu1jBEgEul9h9GKrIwuWF4hdsYC7JjTEFORoGmFbdVNcRjFlbPbFUrkshhTIWX1SG5tmx
2GCJa1i+ctqgAEJ2sSdZTM3jutRc2aZ/uyt11UZEvexAXFm33Vmf8Wr3BvzWLxmKlRK6msrVMNI4
/Bk7WxU7NtBDTdFlodSLwWBBs9ZwF8w5wJwMoD23ESJOztmpetIqYpygC04q18NhWoXdXBC5VD0t
A/hJ8LySt7ecMcfpuKqCCwW5Mc0IW7siC/acjopVHHZDdvDibvDfqCl158ikh4tq8bsIyTYYZe5Q
Q7hdctUoOeFTPiUs2itP3YqeUFDgb5rE1RkmiQF1cwmbOwIDAQABo4IBSjCCAUYwHwYDVR0jBBgw
FoAUwHqYaI2J+6sFZAwRfap9ZbjKzE4wHQYDVR0OBBYEFJfCJ1CewsnsDIgyyHyt4qYBT9pvMBIG
A1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6
Ly9nMS5zeW1jYi5jb20vY3Jscy9ndGdsb2JhbC5jcmwwLwYIKwYBBQUHAQEEIzAhMB8GCCsGAQUF
BzABhhNodHRwOi8vZzIuc3ltY2IuY29tMEwGA1UdIARFMEMwQQYKYIZIAYb4RQEHNjAzMDEGCCsG
AQUFBwIBFiVodHRwOi8vd3d3Lmdlb3RydXN0LmNvbS9yZXNvdXJjZXMvY3BzMCkGA1UdEQQiMCCk
HjAcMRowGAYDVQQDExFTeW1hbnRlY1BLSS0xLTU2OTANBgkqhkiG9w0BAQsFAAOCAQEANevhiyBW
lLp6vXmp9uP+bji0MsGj21hWID59xzqxZ2nVeRQb9vrsYPJ5zQoMYIp0TKOTKqDwUX/N6fmS/Zar
RfViPT9gRlATPSATGC6URq7VIf5Dockj/lPEvxrYrDrK3maXI67T30pNcx9vMaJRBBZqAOv5jUOB
8FChH6bKOvMoPF9RrNcKRXdLDlJiG9g4UaCSLT+Qbsh+QJ8gRhVd4FB84XavXu0R0y8TubglpK9Y
Ca81tGJUheNI3rzSkHp6pIQNo0LyUcDUrVNlXWz4Px8G8k/Ll6BKWcZ40egDuYVtLLrhX7atKz4l
ecWLVtXjCYDqwSfC2Q7sRwrp0Mr82A==
-----END CERTIFICATE-----
```

**Comment by lgarron** [comment]
*woo*

![screen shot 2016-11-16 at 18 00 49](https://cloud.githubusercontent.com/assets/248078/20373420/9f95926e-ac26-11e6-9831-7cc0ba7b41e1.png)

**Comment by lgarron** [comment]
Alright, we're live. Thanks so much, @AGWA.

@marumari, this error is only in Chrome. How do you weigh on putting this subdomain on the home page?

**Comment by marumari** [comment]
I'm okay with it being on the home page. There are a number of pages that Firefox and Chrome treat differently anyways.

**Comment by lgarron** [comment]
Alright. Turns out Chrome is still finalizing some of the code related to this error, so let's wait until at least that is done.
