### ISSUE TITLE
4 subdomains have expired certificates

### ISSUE THREAD

**Issue by BlackthornYugen** [chromium/badssl.com#240]
# Expired last month: 
https://sha1-2016.badssl.com/
https://mozilla-old.badssl.com/
![image](https://cloud.githubusercontent.com/assets/3138467/21723704/74033128-d3ff-11e6-9184-70b307839f76.png)

# Expired yesterday:
https://very.badssl.com/
https://sha1-2017.badssl.com/
![image](https://cloud.githubusercontent.com/assets/3138467/21723703/716eb216-d3ff-11e6-9fb2-37ea15260c3a.png)

**Comment by lgarron** [comment]
Indeed. #217 is the general bug.

I'll update `mozilla-old` and `very` to use SHA-256, though.
