### ISSUE TITLE
Background Colour

### ISSUE THREAD

**Issue by ByJamesBurton** [chromium/badssl.com#259]
Shouldn't we use hex colours instead of using the default red, green and grey colours?

**Comment by ByJamesBurton** [comment]
It would give the site more consistent look across all browsers.

**Comment by marumari** [comment]
Each of those colors is defined as a specific hex value in the HTML specification, aren't they?  They should all look the same across each browser.

**Comment by ByJamesBurton** [comment]
Yeah, they are in the HTML specification but I feel that the colours could do with slight change.

**Comment by marumari** [comment]
Well that's a very different issue than what you opened.  :)

**Comment by ByJamesBurton** [comment]
You got me. :)

**Comment by ByJamesBurton** [comment]
I think the red could be tone down from #FF0000 to #c50000.

**Comment by lgarron** [comment]
I like our bold colors. ;-)

**Comment by ByJamesBurton** [comment]
Okay, I still prefer a good smooth colour. Better on the eyes. :)

**Comment by ByJamesBurton** [comment]
Closing this issue for now.
