### ISSUE TITLE
dh-composite uses prime modulus

### ISSUE THREAD

**Issue by t47** [chromium/badssl.com#260]
I'm assuming that the test is supposed to be about composite number used as modulus (correct me if I'm wrong, the explanation is not too explicit). The modulus that's currently used is different from the one that was originally intended to be used (https://github.com/chromium/badssl.com/issues/40), and it is probably a prime (after 100 rounds of Miller-Rabin).

**Comment by lgarron** [comment]
Oha. Would you care to send a PR to fix? :-)
