### ISSUE TITLE
HTTPS Everywhere link should be http

### ISSUE THREAD

**Issue by leonelwilliams** [chromium/badssl.com#266]
The HTTPS Everywhere link on the main page should probably be using http:// instead of https:// -- linking directly to https:// prevents HTTPS Everywhere from stepping in and doing the upgrading (or seeing if HTTPS Everywhere *isn't* doing the upgrading)

**Comment by lgarron** [comment]
(For now, let's keep using the test image in the footer.)

**Comment by leonelwilliams** [comment]
Ah! Missed that. My bad 😅
