### ISSUE TITLE
Link to invalid-expected-sct from home page

### ISSUE THREAD

**Issue by AGWA** [chromium/badssl.com#267]
(Followup to #215)

I believe that Chrome's handling of this error has settled down, so would it make sense to add a link from the home page?

**Comment by lgarron** [comment]
Sure. I'll happily accept a PR, or if you just want me to do it, let me know.

@marumari, are you fine with putting this at the end of the red triangles of the "Certificate" section? Or do you want to create a separate place for it? (A "Certificate Transparency" section?)

**Comment by marumari** [comment]
I think a separate section would be good.  I think there will continue to be more CT stuff in the future.
