### ISSUE TITLE
please add cert with combined issues

### ISSUE THREAD

**Issue by devZer0** [chromium/badssl.com#271]
could you perhaps add a certificate with a combination of different issues?

 for example self-signed, non-matching URI and also expired?
 
 such cert is causing gui-problem in firefox, which renders the exception dialogue completely unusable (as the buttons are not visible anymore).

see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1347859

**Comment by lgarron** [comment]
We discussed these at #150; let's continue there.
