### ISSUE TITLE
hsts.badssl.com throws mixed content warning.

### ISSUE THREAD

**Issue by konark-cliqz** [chromium/badssl.com#291]
The test https://hsts.badssl.com/ throws a mixed content warning, not sure if it's by design. The image: `http://hsts.badssl.com/hsts-test/status.svg` is the one which is causing the warning.
<img width="1057" alt="screen shot 2017-05-03 at 18 00 57" src="https://cloud.githubusercontent.com/assets/10497229/25669788/ec32d662-302a-11e7-9005-2abc22e07cd7.png">

**Comment by lgarron** [comment]
This is how the test image at the bottom of the page works.

See #13 #77 #239
