### ISSUE TITLE
Add preact-cli and webpack-dev-server certificates to Known Bad?

### ISSUE THREAD

**Issue by ngyikp** [chromium/badssl.com#297]
https://medium.com/@mikenorth/webpack-preact-cli-vulnerability-961572624c54
 
Certs are here:
https://github.com/developit/preact-cli/blob/883c0822e9b7793585fe93c0b003477d037269c0/src/resources/key.pem
https://github.com/developit/preact-cli/blob/883c0822e9b7793585fe93c0b003477d037269c0/src/resources/cert.pem
 
https://github.com/webpack/webpack-dev-server/blob/662bc31a4fc44b6888b5a0baff9ee96fef049cdb/ssl/server.pem

**Comment by lgarron** [comment]
Sounds good!

If someone wants to take this on, I'm happy to accept a PR.
It should be easy to copy everywhere that "superfish" appears and adapt it to these certs: https://github.com/chromium/badssl.com/search?utf8=%E2%9C%93&q=superfish&type=
