### ISSUE TITLE
revoked.badssl.com

### ISSUE THREAD

**Issue by lgarron** [chromium/badssl.com#30]

**Comment by lgarron** [comment]
https://test-sspev.verisign.com:2443/

**Comment by glestel** [comment]
Regarding https://github.com/lgarron/badssl.com/issues/120 I concur that having a revoked subdomain would be useful

**Comment by lgarron** [comment]
https://revoked.badssl.com/ is live.

Requesting revocation right now. Revocation should be safe for CRLSets, since the new cert has a new key, and therefore a unique SPKI.

**Comment by lgarron** [comment]
Success!

<img width="1044" alt="screen shot 2016-09-02 at 14 42 16" src="https://cloud.githubusercontent.com/assets/248078/18219032/7639f982-711b-11e6-84e5-e6cd7a0c9f66.png">

**Comment by marumari** [comment]
Brilliant choice of browsers, I might add.

**Comment by lgarron** [comment]
Here's the whole lot. ;-)

<img width="1866" alt="screen shot 2016-09-02 at 14 50 58" src="https://cloud.githubusercontent.com/assets/248078/18219420/56f373ca-711e-11e6-9953-1c07ab459154.png">

![crywzvyusaa0qsb](https://cloud.githubusercontent.com/assets/248078/18219441/71ebc9f2-711e-11e6-9f77-e7084574eaa2.jpg)
(Edge screenshot via Kyle Pflug [on Twitter](https://twitter.com/kylealden/status/771829012758827010).)

**Comment by marumari** [comment]
Weird that Chrome still displays it, even knowing that the certificate is revoked.

**Comment by lgarron** [comment]
> Weird that Chrome still displays it, even knowing that the certificate is revoked.

Old OSX bug. That's what we get for trying to use native idioms and UI where possible. :-/
