### ISSUE TITLE
Default to 2048-bit DH for `tls-defaults` (for clients that prefer DH)

### ISSUE THREAD

**Issue by luis140219** [chromium/badssl.com#302]
I cannot access the badssl.com website or any of its subdomains, with a "Could not show this page" error in Internet Explorer 11.

**Comment by lgarron** [comment]
We recently migrated servers to Ubuntu 17.04 (and the latest `nginx` that comes with it).

Is there any more information with the error?

**Comment by luis140219** [comment]
I've set up my registry such that DH <2048 bits is rejected. SSL Labs reports "This server supports weak Diffie-Hellman (DH) key exchange parameters. Grade capped to B.": your server sends my computer a 1024-bit Diffie-Hellman group and, because of the registry settings, the group is rejected. This also occurs when I try to connect to some other servers around the Internet, such as knowledge.symantec.com, www.wook.pt and others.

**Comment by lgarron** [comment]
Sounds like you should be able to connect to at least one subdomain: https://static-rsa.badssl.com/
Does https://ecc256.badssl.com/ or https://ecc384.badssl.com/ also work?

(If none of those do, then you probably have a different problem.)

> I've set up my registry such that DH <2048 bits is rejected.

But does it still *offer* such cipher suites? That would be a bug in your configuration.

In general, badssl.com (especially the home page) needs to allow a wide range of client TLS settings to be useful for testing. However, it *should* be choosing ECDSA when possible: https://github.com/chromium/badssl.com/blob/master/nginx-includes/tls-defaults.conf#L8

Could you let me know what OS and browser you're using?

**Comment by luis140219** [comment]
Static-RSA and the ECC test servers do work.

I've changed my registry settings last month such that DHE/AES-GCM suites are the preferred suites.

The fix is to use 2048-bit or bigger Diffie-Hellman by default.

**Comment by lgarron** [comment]
> The fix to this issue is to use 2048-bit or bigger Diffie-Hellman by default.

Hmm, perhaps we can set explicit `dhparam` to 2048 for `tls-defaults`: https://github.com/chromium/badssl.com/blob/master/nginx-includes/tls-defaults.conf

This is low priority for me, but I'm happy to take a PR.

**Comment by luis140219** [comment]
PR: #325

**Comment by christhompson** [comment]
Thanks for the PR! This will go out in the next deployment.

**Comment by lgarron** [comment]
Thanks for picking up on the pending PR, @christhompson!
