### ISSUE TITLE
Add subdomain with sometimes bad certificate

### ISSUE THREAD

**Issue by johnmellor** [chromium/badssl.com#306]
Would it be possible to add a subdomain that serves either a valid or invalid certificate depending on the path you visit?

e.g. https://sometimes.badssl.com/good would return a valid certificate,
and https://sometimes.badssl.com/bad would serve an invalid certificate (e.g. self-signed)

Ideally the good one would also store "sensitive" data into localStorage and cookies (with the `Secure` flag, and both with and without `HttpOnly`), etc.

It would be useful for testing to what extent browsers share cookies/localStorage/etc from valid certificates to invalid certificates after users click through interstitials.

**Comment by lgarron** [comment]
> e.g. https://sometimes.badssl.com/good would return a valid certificate,
> and https://sometimes.badssl.com/bad would serve an invalid certificate (e.g. self-signed)

Unfortunately, that is literally not possible with a straightforward TLS server. :-/

Do you have more specific test scenarios/bugs in mind?

**Comment by johnmellor** [comment]
Ah, no worries then - thanks!

I was wondering if an active network attacker could clickjack interstitials in order to steal cookies etc from https iframes they were MITMing with an invalid certificate, but fortunately I've tested with [jsbin.com/gekeje](https://jsbin.com/gekeje) and at least Chrome, Firefox, IE and Edge all outright block bad SSL in iframes (rather than allowing click through).
