### ISSUE TITLE
Mark dh1024 and dh2048 as red on the front page

### ISSUE THREAD

**Issue by firewave** [chromium/badssl.com#313]
dh1024 and dh2048 both fail in Chrome and Edge, but work in Firefox. I have no other browser at hand for testing this.
Unfortunately I cannot provide more data on this since I have no idea if the issue is with the domain or the browsers.

**Comment by lgarron** [comment]
Some browsers, so this is working as intended.

dh1024 are not secure per se, but they are recommended against since Logjam. We should probably mark them as red.

**Comment by christhompson** [comment]
This should now be deployed.
