### ISSUE TITLE
Chrome 62 Insecure Form Wanrings

### ISSUE THREAD

**Issue by heyfletch** [chromium/badssl.com#316]
[Chrome 62 will trigger Not Secure warnings when typing in any form](https://blog.chromium.org/2017/04/next-steps-toward-more-connection.html) starting October 17, 2017, or for any HTTP form in incognito mode. 

Can we add a link to a regular HTTP form page? Even a simple search field.

**Comment by lgarron** [comment]
> Can we add a link to a regular HTTP form page? Even a simple search field.

We have a bunch of HTTP input test domains:
https://badssl.com/#http-input

(In addition to http.badssl.com)

Let me know if you think we should have a case that is not covered by those.

**Comment by heyfletch** [comment]
I might be missing something, but I do not see any URL that is Http and has a simple form field on it. Can you show me? None of those you mentioned have this.

**Comment by lgarron** [comment]
http://http-password.badssl.com/ contains a single password field.
http://http-login.badssl.com/ has a simple form.

**Comment by heyfletch** [comment]
Both of those sites cause errors due to reasons other than being a simple totally fine form on an HTTP site. They both are flagged in Chrome 58 - 61, so it's not the behavior that we are talking about for Chrome 62 that 1000s of websites owners are going to start finding out they are being flagged by Chrome for normal forms. 
https://blog.chromium.org/2017/04/next-steps-toward-more-connection.html

http://http-password.badssl.com/ is flagged due to a bad form. We are talking now about good forms.

http://http-login.badssl.com/ has a password field, so that's been flagged for a while now. 

It would be great to have that same page, except with a simple name field or any non-password field so that we can show the world "normal, working" forms are flagged by Chrome.

**Comment by heyfletch** [comment]
Ie, both of those pages are flagged because they have password fields. Starting Oct 17, Chrome will show Not Secure for ALL forms, not just password ones, so makes sense to have an example of that.

**Comment by heyfletch** [comment]
Also, Chrome's behavior is different for regular forms than it is for those password forms. For password form pages, Chrome immediately shows Not Secure. For regular forms, Chrome does not show Not Secure until a user starts typing in any form field. Then it shows Not Secure.

So my suggestion is to create a http://http-form.badssl.com/ page with one field.

**Comment by ericlaw1979** [comment]
http://http.badssl.com/mixed/form/ works.

http://webdbg.com/test/forms/text.html is what I've used to test the feature.

**Comment by lgarron** [comment]
Ah, I see. That does sound like a reasonable request.

http://http-credit-card.badssl.com/ already has the behaviour all forms will have in Chrome 62, if you just need to demonstrate how it looks.

I'd be happy to accept a PR that implements `http.badssl.com/input/text`, and optionally also  `http-text-input.badssl.com`
