### ISSUE TITLE
Move `http` on the front page together with HTTP input

### ISSUE THREAD

**Issue by Flimm** [chromium/badssl.com#320]
Chrome 62 has this new feature:

> As we announced previously, starting in Chrome 62, when a user enters data on an HTTP page, Chrome will mark the page as "Not Secure" with a label in the address bar. This label will also be shown in Incognito Mode for all HTTP pages.

I would like to be able to test this out. Funnily enough, it's harder then I thought it would be to find HTTP websites to test it on. It would be great if badssl.com had a subdomain without SSL, maybe one with a password input and one without.

**Comment by girst** [comment]
http://http.badssl.com

**Comment by lgarron** [comment]
For plain HTTP, we have http.badssl.com (and I also recommend neverssl.com if you need a site completely dedicated to that purpose).

Other cases are at https://badssl.com/#http-input , and we also have http://http.badssl.com/mixed/form/

**Comment by Flimm** [comment]
My bad folks, I didn't spot the "http" entry under "Miscellaneous" in the home page of badssl.com . Thank you!

**Comment by lgarron** [comment]
Actually, good point.
