### ISSUE TITLE
How about a 4096-bit key length certificate test

### ISSUE THREAD

**Issue by hilgart** [chromium/badssl.com#337]
It took me an hour of searching to find a site with a 4096-bit key length certificate. I finally did: www.bluehost.com. But as a central repository for these sorts of things it'd be nice if you guys simply had a web page with one for conducting SSL client tests.

**Comment by lgarron** [comment]
Interesting to know that 4096-bit certs are useful for someone's tests. Could you let us know what is useful about a 4096-bit cert in particular? (vs. other large sizes)

**Comment by hilgart** [comment]
Well, there's a GoDaddy-one I had to test that's about to go live May 1st.
I guess it's interesting because GoDaddy is beginning to push them a bit. I
honestly didn't know if our old browsers were compatible; what our SSL
interceptor would do with it. Those sorts of things. I guess - but I don't
really know - that it will become somewhat common. I haven't seen anything
between 2048 and 4096, nor anything larger than 4096.

**Comment by lgarron** [comment]
I see; 4096-bit is not really necessary, but probably the most realistic RSA key size we're missing.

@christhompson, is it alright with you if I add code and deploy a 4096-bit cert to production?

**Comment by hilgart** [comment]
Hi Chris, Are you still figuring out how to deploy? I still don't see an
example certificate of this type on the badssl.com web site.
Thanks,
John

**Comment by christhompson** [comment]
This should be live now. Let me know if anything isn't working as expected.

(This got delayed while I was working on some other server work, but I've pushed an update to the current config for now.)

**Comment by hilgart** [comment]
OK. I see it. Thanks Chris.
Regards,
John
