### ISSUE TITLE
eDellRoot certificate has expired

### ISSUE THREAD

**Issue by djcater** [chromium/badssl.com#344]
This causes:
```
NET::ERR_CERT_DATE_INVALID
Subject: edellroot.badssl.com

Issuer: eDellRoot

Expires on: 3 Dec 2017

Current date: 5 May 2018
```
In Chrome. Whereas the other known-bad ones get `NET::ERR_CERT_AUTHORITY_INVALID`.

As it has now expired, it's not really testing what it's meant to. It would be good to generate a new certificate.

**Comment by christhompson** [comment]
This should now be fixed on the site. You should see a new certificate with an expiration in 2020.

**Comment by lgarron** [comment]
@christhompson, could you also regenerate `dsdtestprovider` and `superfish`? They're expiring soon?

(I had a plan to add expiration dates to a calendar, but never got around to it. Perhaps GitHub milestones would be an easy way to batch needed updates once a year?)
