### ISSUE TITLE
Prod flag not working on extended-validation page

### ISSUE THREAD

**Issue by christhompson** [chromium/badssl.com#354]
We check that the domain is prod when building the HTML for extended-validation.badssl.com, but it appears that this currently isn't working, and we're instead showing the test-domain text on the live page:

https://github.com/chromium/badssl.com/blob/0b1b3a240d211dead87f1356b2d15aa66d152f25/domains/cert/extended-validation/index.html#L14-L20

The domain gets set when starting the Jekyll build:

https://github.com/chromium/badssl.com/blob/0b1b3a240d211dead87f1356b2d15aa66d152f25/domains/cert/extended-validation/index.html#L14-L20

And is then compared:
https://github.com/chromium/badssl.com/blob/0b1b3a240d211dead87f1356b2d15aa66d152f25/_plugins/environment_variable.rb#L9

Tagging @april who wrote the original version of this configuration. Any ideas?

**Comment by april** [comment]
Hmm, that's strange. And you ran `make jekyll-prod`?

**Comment by christhompson** [comment]
Yeah, adding verbose flags to `jekyll build` call doesn't help, but adding `STDERR.puts site.config` to environment_variable.rb after everything gets set:

`"domain"=>"badssl.com", "prod"=>false, "http-domain"=>"http.badssl.com", `

So `domain` appears to be set correctly but the `prod` conditional appears to not be working right.

Logging `STDERR.puts ENV` before the config gets set appears to show that `ENV['PROD_DOMAIN']` is empty. `ENV['DOMAIN']` is correctly set.

I think the fix is to change the Makefile to:

```
################ Definitions ################

export TEST_DOMAIN = badssl.test
export PROD_DOMAIN = badssl.com
```
so that the variables are included in the ENV passed to the ruby/jekyll. I'll double check this with a local change on the server and then upload a PR with the fix if it solves it.
