### ISSUE TITLE
Certificate Transparency site not triggering correct interstitial

### ISSUE THREAD

**Issue by livvielin** [chromium/badssl.com#358]
https://invalid-expected-sct.badssl.com/ triggers the NET::ERR_CERT_SYMANTEC_LEGACY interstitial in newer versions of Chrome.

**Comment by christhompson** [comment]
As a workaround for testing, the Symantec distrust can be disabled using the `--disable-features="LegacySymantecPKI"` flag passed to Chrome on the command-line.

@april Do you know who to contact to re-issue this certificate? I'm happy to make a new CSR if needed.

**Comment by FranklinYu** [comment]
Any update?

**Comment by april** [comment]
I do, I think! Sorry I missed the initial notification on this, but I'll shoot you the contact info when I get back to work next week.  :)

**Comment by RJPercival** [comment]
This has been somewhat superceded by #372 (the certificate expired).

**Comment by christhompson** [comment]
We've added no-sct.badssl.com to hit this use case. We likely won't be able to get a new invalid sct cert, so closing this out.
