### ISSUE TITLE
Cert for self-signed.badssl.com has expired

### ISSUE THREAD

**Issue by christhompson** [chromium/badssl.com#359]
The cert for https://self-signed.badssl.com/ appears to have expired yesterday (2018-08-07). I'll try to re-generate it and push the new cert live soon.

Coincidentally, this gives us a production cert for #150 if we wanted to add a new subdomain :-)

**Comment by drwetter** [comment]
We're using this domain (amongst others) for CI for [testssl.sh](https://github.com/drwetter/testssl.sh) (in https://github.com/drwetter/testssl.sh/blob/2.9dev/t/31_badssl.com.t). Any idea when this will be renewed?

**Comment by christhompson** [comment]
I've regenerated the self-signed cert on the server, so this should now be fixed. Let me know if it is still causing issues.

**Comment by drwetter** [comment]
It shows still the old certificate :-(

![screenshot_20180815_162633](https://user-images.githubusercontent.com/8036727/44153315-37304f02-a0a8-11e8-9b77-85b6aa6dcdc0.png)

**Comment by christhompson** [comment]
Ahh you're right -- I closed to soon when I wasn't seeing the expired interstitial. The new cert is live and I've double checked that it is valid until 2020.

**Comment by drwetter** [comment]
Thanks!

**Comment by mikhail-chebakov** [comment]
Thanks, Chris!

**Comment by erikcorry** [comment]
For some reason the old cert (that is expired) seems to be back.
![image](https://user-images.githubusercontent.com/833514/59329901-4b026a80-8cf0-11e9-96af-63b69c471baf.png)

**Comment by firewave** [comment]
The certificate apparently went bad at around 3 PM UTC yesterday. It seems several of the certificates were affected, but now just the self-signed one seems wrong.

**Comment by christhompson** [comment]
Ah, sorry about that (and thanks for catching it). I ran a re-deploy yesterday and it looks like it picked up an old cert for it. I'll get a fix in soon.

**Comment by christhompson** [comment]
The live cert on self-signed.badssl.com should now be updated and not expired.

I'm going to leave this open to track the better fix (removing https://github.com/chromium/badssl.com/blob/master/certs/sets/prod/pregen/chain/wildcard-self-signed.pem from the repo so that it gets re-generated on every deploy).

**Comment by christhompson** [comment]
We decided to not regenerate the self-signed cert on every deploy (so that it stays somewhat stable over time), so closing this out. We're working to track cert expiry more closely instead.

**Comment by etnbrd** [comment]
It appears the certificate is expired again on https://self-signed.badssl.com/
`The certificate for self-signed.badssl.com expired on 8/8/2018.`

**Comment by drwetter** [comment]
Yup, we again see Travis failing, see https://github.com/drwetter/testssl.sh/pull/1378#issuecomment-567124504

**Comment by firewave** [comment]
I added #426 for this - didn't want to re-open an old one.
