### ISSUE TITLE
invalid-expected-sct expires on 2018-11-17

### ISSUE THREAD

**Issue by AGWA** [chromium/badssl.com#372]
The certificate for `invalid-expected-sct.badssl.com` expires in 21 days, on November 17, 2018.  Now that Symantec is kaput, there are no CAs intentionally issuing certificates with invalid embedded SCTs, so I won't be able to renew this cert.  A CA might be willing to do this as a special request, but it would be extremely special.

**Comment by lgarron** [comment]
> A CA might be willing to do this as a special request, but it would be extremely special.

Just to confirm: this would be weird, but would not violate any Baseline Requirements, right?

**Comment by lgarron** [comment]
Also, `invalid-expected-sct.badssl.com` was a workaround for the fact the SCT requirement was only enforced for Symantec. `missing-sct.badssl.com` would probably do the trick now.

**Comment by AGWA** [comment]
Embedding an invalid SCT in a certificate is not inherently a violation of the BRs or any root program requirements.  (That said, the way Symantec was doing it was a violation, since they were also signing pre-certificates that were binding commitments to misissue.)

Good point about `missing-sct.badssl.com` being sufficient.  DigiCert allows you to disable CT logging for a certificate (see section 1.4 of https://www.digicert.com/certcentral-support/certcentral-ssl-certificate-ct-logging-guide-v1.2_2018-03-26_opt.pdf)

**Comment by lgarron** [comment]
> How about using a certificate without embedded SCT and send an invalid SCT together with it through TLS extension?

This isn't possible using `nginx`, right?

**Comment by JemmyLoveJenny** [comment]
@lgarron 
> > How about using a certificate without embedded SCT and send an invalid SCT together with it through TLS extension?
> 
> This isn't possible using stock `nginx`, right?

It IS POSSIBLE with nginx, however you need to recompile it with nginx-ct module.  

And  I don't think sending an invalid SCT is necessary, as the purpose of invalid-expected-sct.badssl.com is to cause ERR_CERTIFICATE_TRANSPARENCY_REQUIRED. So that you can use a certificate without embedded SCT and configure nginx to send "Expect-CT" (enforce) Header in HTTP Response.  

When the browser receives the "Expect-CT" Header, it would try to verify the SCT, and thus, cause this ERROR.

**Comment by RJPercival** [comment]
This certificate has expired but it's still live on badssl.com - it should be removed or replaced with https://missing-sct.badssl.com. However, https://missing-sct.badssl.com doesn't seem to be properly configured (I get NET::ERR_CERT_COMMON_NAME_INVALID on that domain).

**Comment by FranklinYu** [comment]
@RJPercival For the missing-SCT site I get `NET::ERR_CERT_AUTHORITY_INVALID` in Chrome

**Comment by RJPercival** [comment]
The full error I see is:
```
This server could not prove that it is missing-sct.badssl.com; its security certificate is from badssl-fallback-unknown-subdomain-or-no-sni. This may be caused by a misconfiguration or an attacker intercepting your connection.
```

**Comment by christhompson** [comment]
We've added https://no-sct.badssl.com/ to address this test case :-)
