### ISSUE TITLE
Css help

### ISSUE THREAD

**Issue by Bundy01** [chromium/badssl.com#381]
Hello,
this is not an issue but i modify a css file that changes the color of the address bar according to the security of the site.

I would like to know the css code for the page: http://http-credit-card.badssl.com/
Exemple: for http://http-login.badssl.com/ it's `#urlbar[pageproxystate='valid'] #identity-box.insecureLoginForms:after`.

**Ps: For firefox 64**
Thank you for your help.

**Comment by lgarron** [comment]
@april might be able to help you with Firefox-specific code, but unfortunately I don't think anything in badssl.com can directly help you with this.

**Comment by april** [comment]
I'm not exactly sure what you're asking for? Websites have no ability to change the color of the address bar, the browser is simply choosing its own styling based on what you are doing.

**Comment by Bundy01** [comment]
Hello,
@april: I add the file /chrome/userCrome.css in the Firefox profile. I posted in a Firefox forum but I didn't get the answer. I'll keep looking.
