### ISSUE TITLE
1000-sans cert expired on Feb 17 2019

### ISSUE THREAD

**Issue by robrich** [chromium/badssl.com#383]
Because this certificate is expired, it's actually testing the expired cert case rather than the 1,000 sans case.

**Comment by mimi89999** [comment]
Any news on this? Will this certificate ever get renewed?

**Comment by april** [comment]
I haven’t found a good way to get them renewed. Thankfully, they’re mostly for UI tests and so are fine with verification turned off.

If someone can get a CA to help, that would be amazing.

**Comment by robrich** [comment]
Are CAs balking because they don't like building certs with specifically bad details?  Or is this a cost issue in buying this many certs?

**Comment by dangeredwolf** [comment]
They still haven't updated this.

**Comment by april** [comment]
Yes, it’s a cost issue. It would be tens of thousands of dollars without support from a CA. Since it’s mostly used for seeing how UX’s break, it shouldn’t be a big deal that it’s expired, as you can always manually trust it.

**Comment by robrich** [comment]
@april can we leverage Let's Encrypt for this?  A quick node script we run once-a-month that pulls all the certs and saves them into a static site could work. I could help with a bit of research on their limits (1,000 SANs, revoking, etc)

**Comment by april** [comment]
Let’s Encrypt limits you to 100 domains per certificate unfortunately.

**Comment by christhompson** [comment]
This is now deployed. We were able to get a new 1000-sans cert from DigiCert.
