### ISSUE TITLE
revoked.badssl.com is about to expire

### ISSUE THREAD

**Issue by sfionov** [chromium/badssl.com#404]
It is about to expire at 2019-09-11

**Comment by sfionov** [comment]
Also it seems to be missing from Chrome CRLSets now.
So the test is unusable.

**Comment by rohitratri** [comment]
Hey folks! When do you plan to update the cert? 
This is a very useful resource - hope to see it back in action again soon...

**Comment by christhompson** [comment]
Yep, we'll work on getting this back up. We need to get a new cert and then revoke it, which is a little more involved than normal.

**Comment by mikhail-chebakov** [comment]
Hello, guys!
Is there any progress on this?

We really appreciate this resource. Hoping it will come back.

**Comment by naumanshah03** [comment]
Any update on this issue?

**Comment by B3nac** [comment]
Looking forward to this cert hopefully getting renewed. For anyone looking for a site to test certs revoked by a CRL https://revoked.grc.com/ still works.

**Comment by cr** [comment]
This is breaking non-critical automated OCSP-based testing at Mozilla. We can work around for now, but getting away from the broken fallback certificate that's currently being delivered by the server and restoring the original behavior would be highly preferable.

Thanks @B3nac for the alternate! This will definitely be our temporary workaround.

**Comment by christhompson** [comment]
This is now deployed. The Chrome CRLSet update is in-progress and should reach Chrome clients in ~1 day. I'll leave this open until we've handled other revocation list followup.

**Comment by naumanshah03** [comment]
SSL Labs now reports it correctly as revoked. Thank you

https://www.ssllabs.com/ssltest/analyze.html?d=revoked.badssl.com&hideResults=on

**Comment by christhompson** [comment]
Closing as it looks like everything has propagated in at least Chrome and Firefox.
