### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by dryiceza** [chromium/badssl.com#406]
Hi! I really find this website useful!

Is there any plan to add TLS 1.3 under the list of protocols?

Thanks!

**Comment by christhompson** [comment]
Merging to #332 which has our current discussion on adding support for TLS 1.3. To summarize: It's on my list of things to work on sometime soon-ish, but it will require a fair amount of work as it looks like we'll need to have two different versions of NGINX running to support it (so we'll likely need to container-ify parts of the infrastructure for serving different subdomains).

**Comment by dryiceza** [comment]
Great thanks! Good to know that it's being worked on! I appreciate it!
