### ISSUE TITLE
self-signed certificate has expired

### ISSUE THREAD

**Issue by djcater** [chromium/badssl.com#418]
https://self-signed.badssl.com/

I see that the auto-generating part was removed, but I think the static in-repo certificate should be regenerated as per: "we'll just track the expiration and regenerate in-tree when needed" from https://github.com/chromium/badssl.com/pull/390#issuecomment-540111190_

**Comment by christhompson** [comment]
Ahh, same bug as in #417 -- thanks for catching these. I've made a note to myself in my deploy playbook and updated this one as well. This should be fixed on the site and #419 will make it so I don't accidentally pull in the expired one from the repo again.
