### ISSUE TITLE
Client Certificate Expired

### ISSUE THREAD

**Issue by CoderKahn** [chromium/badssl.com#422]
Hi, your client certificate PKCS#12 and PEM obtainable from https://badssl.com/download/ have expired yesterday.

Could you provide a new one.

Sincerely 

CoderKahn

**Comment by vladimir-ikryanov** [comment]
@lgarron @april could you please comment on this issue? Do you happen to know when this issue might be fixed?

**Comment by christhompson** [comment]
Sorry for missing these during our recent updates -- I forgot to add them to my tracking spreadsheet (but they are not, so hopefully next time I'll remember to update them before they expire).

I've regenerated the client certificates on https://badssl.com/download/, so if you re-download and re-install them the test pages should now be working. Let me know if there are any remaining issues :-)
