### ISSUE TITLE
self-signed certificate expired

### ISSUE THREAD

**Issue by firewave** [chromium/badssl.com#426]
The certificate expired on August 8th 2018.  The day before yesterday it was still fine.

Interestingly that's the same date as the expired certificate in #415.

**Comment by wbond** [comment]
I also started hitting this issue recently.

**Comment by christhompson** [comment]
Fixed -- I accidentally reverted it back to the previous cert when deploying some other changes last week.

**Comment by wbond** [comment]
Thanks @christhompson!

**Comment by drwetter** [comment]
It has a problem again

**Comment by christhompson** [comment]
Fixed, accidentally reverted during a deploy yesterday (I've taken an action item to fix this in the deploy process to prevent it from happening again).
