### ISSUE TITLE
self-signed certificate expired

### ISSUE THREAD

**Issue by drwetter** [chromium/badssl.com#429]
self-signed.badssl.com: Certificate Validity (UTC)   expired (2016-08-08 23:17 --> 2018-08-08 23:17)

See also #426 and #415. 

Seems like an intrinsic problem to me?

**Comment by christhompson** [comment]
Yep, I need to fix this in the deployment process (it sometimes happens as a side effect of other updates). Fixed manually on the server.

**Comment by drwetter** [comment]
Thanks
