### ISSUE TITLE
sha1-intermediate.badssl.com cert is expired

### ISSUE THREAD

**Issue by sfionov** [chromium/badssl.com#446]
not valid after 2020-05-31

**Comment by christhompson** [comment]
We changed this to Defunct in #445, but I hadn't updated the live site yet, sorry about that. The site should now list sha1-intermediate under the Defunct section, since we can't get a replacement cert.

**Comment by sydia1103** [comment]
> We changed this to Defunct in #445, but I hadn't updated the live site yet, sorry about that. The site should now list sha1-intermediate under the Defunct section, since we can't get a replacement cert.

I also found this website that has a SHA1 certificate that was recently resigned, and will expire next year. ssg140.impackltd.com.tr Here is the SSL Labs Test https://www.ssllabs.com/ssltest/analyze.html?d=ssg140.impackltd.com.tr
