### ISSUE TITLE
10000-sans.badssl.com fails to load due to SSL error

### ISSUE THREAD

**Issue by faheel** [chromium/badssl.com#457]
I tried to visit 10000-sans.badssl.com using Chrome 85.0.4183.121 and Firefox 81.0, but I always get an SSL error (`ERR_SSL_PROTOCOL_ERROR` on Chrome and `SSL_ERROR_RX_MALFORMED_HANDSHAKE` on Firefox).

### Screenshot of Chrome

![Screenshot from 2020-10-05 19-33-39](https://user-images.githubusercontent.com/11466676/95089881-49a94c80-0742-11eb-80fc-23c7edf28285.png)

### Screenshot of Firefox

![Screenshot from 2020-10-05 19-43-54](https://user-images.githubusercontent.com/11466676/95090665-2632d180-0743-11eb-8735-24a43ea1eb45.png)

I'm not sure whether this is the expected behaviour or if something is wrong, hence the bug report.

**Comment by christhompson** [comment]
Yep, this is expected behavior in most browsers. We try to maintain the expected behaviors for each test case on https://badssl.com/dashboard/, which is a good way to double check. In this case, "Cannot connect" is an OK result (connecting would also be OK, but most clients will fail).
