### ISSUE TITLE
wrong-host.badssl.com certificate has expired

### ISSUE THREAD

**Issue by SamuelNitsche** [chromium/badssl.com#458]
I am using this endpoint to test my application and I see errors that the certificate has expired back in 2018. Can you generate a new one?

**Comment by PavelD** [comment]
I was about to report simillar:

https://no-common-name.badssl.com/ reports following:

Websites prove their identity via certificates, which are valid for a set time period. The certificate for no-common-name.badssl.com expired on 6/23/2020.
 
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by vyrp** [comment]
https://wrong-host.badssl.com/ 's certificate seems to be up to date. I get a not-after value of 2022-05-17T05:00:00.

However, https://no-common-name.badssl.com/ and https://no-subject.badssl.com/ are out of date.

**Comment by vyrp** [comment]
Ohhh, I confused https://wrong-host.badssl.com/ with https://wrong.host.badssl.com/.
* https://wrong-host.badssl.com/ 's certificate has expired.
* https://wrong.host.badssl.com/ 's certificate is up to date.

**Comment by SamuelNitsche** [comment]
I think I confused wrong-host.badssl.com with wrong.host.badssl.com. Thanks @vyrp for bringing this to my attention.
