### ISSUE TITLE
Re-organize the front page

### ISSUE THREAD

**Issue by lgarron** [chromium/badssl.com#46]
![screenshot-badssl com 2015-05-22 00-53-17 1 1](https://cloud.githubusercontent.com/assets/248078/7766343/22f3c9da-001d-11e5-9865-9330be04c00a.png)

Perhaps organize by categories from 9ed944e821f31cd1f1d8c7f2d9e0b479f3f28c08.

**Comment by marumari** [comment]
I actually don't care much for the hiding thing.  I think if everything were well organized, having to scroll through the whole list could be okay.  But I'll poke around on designs for it.  :)

**Comment by marumari** [comment]
See 9ee3215c2b5ab5f6c83bfffcccd9d51c62446d59.

**Comment by marumari** [comment]
I've got a commit in for a newly designed homepage, but you can see what it looks like here:

http://www.twoevils.org/files/tmp/badssl/

**Comment by lgarron** [comment]
> http://www.twoevils.org/files/tmp/badssl/

I like the organization, but it's still very spaced out and the colors are garish (both my fault because of my earlier choices).

I'd prefer something more like https://httpswatch.com/ with a smaller indicator per site.
Or maybe get rid of colors altogether, and use indicators for e.g. things that should result in failures.

**Comment by Hoverbear** [comment]
* I noted was that the colors have no descriptions of what they mean, so they kind of fall meaningless to a visitor.
* It might be good to have short descriptions or links of what the item "means" since not everyone will know each of the variants is all about and why they might need to be concerned with it.

**Comment by marumari** [comment]
I actually like the garish colors, as they make for very nice screenshots. We use badssl a lot for showing how things will be impacted.

That's not the homepage though, just the subpages.

**Comment by lgarron** [comment]
> I noted was that the colors have no descriptions of what they mean, so they kind of fall meaningless to a visitor.

Yeah, it's been a bit tricky to make the colors mean anything. But as @marumari points out, they sure are nice for screenshots and easily knowing what page you're on.

> It might be good to have short descriptions (or links) of what the item "means" since not everyone will know each of the variants is all about and why they might need to be concerned with it.

Yeah, it's a bit unfortunate that some subdomains don't even have explanations when you click on them.
I don't think we owe it to developers to explain why they should care about the problems, but we should make clear what is factually going on with each subdomain. I've filed #103 for this.

**Comment by marumari** [comment]
I'm willing to take this one, provided we can use a library to make my life less terrible, like bootstrap?  Any problems with that?

**Comment by marumari** [comment]
@lgarron, @Hoverbear: How does this look like, for a redesign?  Every site has tooltips, should be responsively designed, etc. etc.:

http://www.twoevils.org/files/tmp/badssl/

**Comment by lgarron** [comment]
> How does this look like, for a redesign?

Honestly, still pretty ugly. (Again, because it still adheres to the ugly layout we currently have, not because your new work.)

It seems that GitHub ate my comment where I said I'd like to avoid using a library like Bootstrap. I prefer to keep things simple when possible, and I don't think it would be a good tradeoff here.

I do like the tooltips, but they don't quite work on mobile.

**Comment by lgarron** [comment]
I'd really prefer to go with [Material design](https://www.google.com/design/spec/material-design/introduction.html), maybe [mvld](https://github.com/lgarron/my-very-lite-design).

**Comment by marumari** [comment]
Sure, but in the meantime we have a new design that makes it 1000x easier to find domains, has nice groupings, and tooltips for most people.  I just don't want to let the desire for the perfect get in the way of the good.  The current frontpage sucks and using this for now doesn't mean committing forever.

It's two JavaScript files and one CSS file.  Hardly the end of the world.  It also massively cleans up the existing scripts and CSS, so honestly it's more simple in many ways.

**Comment by Hoverbear** [comment]
@marumari It looks better than what is currently there. :) Good job with it. Can I help you move forward on this?

**Comment by marumari** [comment]
I'd like to move forward, but @lgarron is the one that controls the actual public facing one and would have to be willing to accept my PR.  I've made some more tweaks for scaling on the version I've been working on.

Sure, it would be great to have it all as this beautiful flexbox beauty -- and somebody we will get there -- but this gets us to something 100x more usable, and it gets us there immediately.

I'm hoping to get some time to redesign things after Mozlando, so hopefully I can do Flexbox / PureJS there, and I'm pretty confident that I can do it.  But if @lgarron  hates the current visual style entirely, then I'll need some guidance on where to take things.

**Comment by lgarron** [comment]
How's https://github.com/lgarron/badssl.com/tree/slight-front-page-redesign for now?

As for direction, I'd really like something like https://httpswatch.com/global

**Comment by Hoverbear** [comment]
@lgarron There is a lot of empty space there, do you see badssl acting more of a large, detailed list rather than a dashboard meant as a router/overview?

**Comment by marumari** [comment]
The current homepage is missing some stuff, fyi:

* all the mixed sites (css, font, iframe, image, form, password) - script uses mixed-script instead of mixed/script
* spoofed-favicon
* the long names
* rc4-md5 (did we just do away with this instead?)

**Comment by Hoverbear** [comment]
@marumari I found this css only tooltip library: http://kushagragour.in/lab/hint/ Do you think that'd be appropriate?

**Comment by lgarron** [comment]
@marumari, what do you think of the page at https://badssl.com/material/ ?
It's heavily inspired by Inbox, and it works pretty well.

In addition, if we want to add longer descriptions, we can avoid tooltips by taking another page from Inbox and putting descriptions to the right of the subdomain names.

![screen shot 2016-08-09 at 18 38 00](https://cloud.githubusercontent.com/assets/248078/17539151/9f8880e2-5e60-11e6-8432-03de7878f04d.png)
<img width="477" alt="screen shot 2016-08-09 at 18 38 17" src="https://cloud.githubusercontent.com/assets/248078/17539150/9f8804d2-5e60-11e6-824d-06a6378f49e1.png">

**Comment by marumari** [comment]
It's a bit spartan for me.  I think it looks better on mobile than on the desktop, where it's a skinny strip down the middle with infinite padding on the side.

**Comment by lgarron** [comment]
Spartan is kind of the goal. :-P
I remember back when *this* looked like a lot:

![badssl](https://cloud.githubusercontent.com/assets/248078/17539487/85168152-5e63-11e6-904e-c3795fd2497a.png)


Anyhow, how's a max-width of 600px for the material groups?
![screen shot 2016-08-09 at 18 59 39](https://cloud.githubusercontent.com/assets/248078/17539497/96aa5376-5e63-11e6-9365-2e3fef886d19.png)

**Comment by marumari** [comment]
I think it looks alright, although it's still lacking in emoji.  I suggest using the power of CSS transforms and emoji, like so:

https://marumari.github.io/crypto-presentation/#/72

**Comment by lgarron** [comment]
How's this?

![screen shot 2016-08-09 at 19 26 31](https://cloud.githubusercontent.com/assets/248078/17539929/3427f826-5e67-11e6-9ecb-494c755dace4.png)

**Comment by lgarron** [comment]
I also tried two columns, but I don't know if I like it (ignore some spacing issues).

![screen shot 2016-08-09 at 20 05 30](https://cloud.githubusercontent.com/assets/248078/17540669/c2d0f0dc-5e6c-11e6-96ce-e43f94cea4e3.png)

**Comment by lgarron** [comment]
Also, how about these?

📜 Certificate
🔑 Key Exchange
🔀 Cipher Suite
⬆️ Upgrade
💬 Miscellaneous
❌ Known Bad
🖼 Mixed Content

**Comment by marumari** [comment]
I think one column is great, and I love those emoji.  :)

**Comment by lgarron** [comment]
@marumari I think I did a decent job getting two columns to work, and I'm getting accustomed to it!

Happy to go back to one column, though. ;-)

![screen shot 2016-08-10 at 12 42 30](https://cloud.githubusercontent.com/assets/248078/17568288/f5384f30-5ef7-11e6-870b-4916a4ea52cc.png)
![screen shot 2016-08-10 at 12 42 49](https://cloud.githubusercontent.com/assets/248078/17568287/f5380390-5ef7-11e6-87d6-566278437446.png)

**Comment by marumari** [comment]
I dig it!  I think everything looks great except for the fact that you're not using Firefox.  :)

**Comment by marumari** [comment]
I particularly appreciate how well it handles word wrapping!

**Comment by lgarron** [comment]
> I particularly appreciate how well it handles word wrapping!

Yeah, I even had to set the icon not to flex in order to compensate! :-)
https://github.com/chromium/badssl.com/commit/c5b34b91ae5e1e9a560fad6e34c37f37aefd2b03#diff-647055304192f621bc3a4b8ca5f5e5a1R96
