### ISSUE TITLE
y?

### ISSUE THREAD

**Issue by redcatpaw** [chromium/badssl.com#469]
Nothing connects to reversed-chain and it's in secure (common)? Nonsense!

**Comment by christhompson** [comment]
`reversed-chain` is currently a bit broken (see https://github.com/chromium/badssl.com/pull/443#issuecomment-784556007) and I should probably remove it from the homepage for now until we resolve that. If we get it working, it would in fact be fine for any client that is able to successfully build a chain to trust it.

(Also, a reminder to be civil in bug reports: https://docs.github.com/en/github/site-policy/github-community-guidelines)
