### ISSUE TITLE
How does the captive portal subdomain work?

### ISSUE THREAD

**Issue by tmann50** [chromium/badssl.com#471]
It would seem that chrome uses a request to http://gstatic.com/generate_204 to determine the presence of a captive portal on a network, but the captive-portal.badssl.com domain shows the chrome captive portal message, even when everything else is available, so it can't be this

How does chrome know that captive-portal.badssl.com "is" a captive portal?

**Comment by lgarron** [comment]
The certificate is hardcoded in Chrome:

https://source.chromium.org/chromium/chromium/src/+/master:components/resources/ssl/ssl_error_assistant/ssl_error_assistant.asciipb;l=14?q=badssl.com&ss=chromium

Hope that answers your question!
