### ISSUE TITLE
no-common-name.badssl.com cannot be resolved to an IP address

### ISSUE THREAD

**Issue by c0r0n3r** [chromium/badssl.com#481]
Checked with the following commands:

    $ dig @1.1.1.1 -t A +short no-common-name.badssl.com
    $ dig @8.8.8.8 -t A +short no-common-name.badssl.com
    $ dig @1.1.1.1 -t AAAA +short no-common-name.badssl.com
    $ dig @8.8.8.8 -t AAAA +short no-common-name.badssl.com

**Comment by lgarron** [comment]
Hmm, I'm also not able to resolve this.

@christhompson, any ideas? We haven't had issues with any of the cert issues affecting DNS resolution, but who knows.

**Comment by christhompson** [comment]
I think it should be working now.

I'd been testing some ACME DNS challenges which I think might have interacted badly with resolution for this subdomain in an unexpected way. I've deleted those records for now, and the hostname appears to be resolving again.
