### ISSUE TITLE
Expired Client Certificate

### ISSUE THREAD

**Issue by danistrebel** [chromium/badssl.com#482]
I just saw that the client cert expired. 
https://badssl.com/download/

Thanks in advance! 

```
 Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            2b:93:6c:e3:2d:82:ce:8b:01:fd:9a:05:95:ac:63:66:aa:01:4c:82
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = California, L = San Francisco, O = BadSSL, CN = BadSSL Client Root Certificate Authority
        Validity
            Not Before: Nov 27 00:19:57 2019 GMT
            Not After : Nov 26 00:19:57 2021 GMT
 ```

**Comment by nielsatencompass** [comment]
I use this badssl certificate in a test. 
When a new one gets created can it be very long dated - like 50 years?

**Comment by christhompson** [comment]
I've regenerated the client certs, but let me know if there are any issues with the new ones. For now they just have a new 2 year lifetime, but this is probably a category of cert that we can automatically update -- I'm planning to work on setting up some automation for the easy cases next quarter so hopefully this can be on the short-list.
