### ISSUE TITLE
badssl.com goes offline due to DNS failure

### ISSUE THREAD

**Issue by dcheung2** [chromium/badssl.com#500]
It is a short term service interruption or it is going to be offline forever ?

https://who.is/whois/badssl.com
show that some chances recently and the domain itself is expiring soon.

> Registrar Info
> NameGoogle LLC
> Whois Serverwhois.google.com
> Referral URLhttps://domains.google.com
> StatusclientTransferProhibited https://www.icann.org/epp#clientTransferProhibited
> Important Dates
> Expires On 2022-04-07
> Registered On 2015-04-07
> Updated On 2022-03-31
>

**Comment by dcheung2** [comment]
the IP 104.154.89.105 seem still up and running

**Comment by lgarron** [comment]
Hmm, I had no trouble accessing a few hours ago, but I can also repro now.

**Comment by christhompson** [comment]
Hmm, I’m not exactly sure what’s going wrong. I did some DNS changes
earlier while working on getting ACME validation working, but they
shouldn’t have affected the main site. I can investigate more and try to
roll back tomorrow morning.

**Comment by pbiggar** [comment]
Confirming site is down for me on various machines with various different HttpClient (Chrome on Mac, linux curl, .NET HttpClient)

**Comment by drwetter** [comment]
I tried from several locations around the world with different upstream NS and all I got was a SERVFAIL

**Comment by christhompson** [comment]
DNS should be back (pending any propagation delays). There might be some further hiccups later today while I work on things, but I'll double check that they're left in a working state so things don't stay down for long.
