### ISSUE TITLE
badssl.com certificate is now expired 

### ISSUE THREAD

**Issue by mstoykov** [chromium/badssl.com#504]
The certificate seemed to have expired a few minutes ago at this time

This specifically for the main site - https://badssl.com/ ,  that list all the ... in practice bad ssl endpoints

**Comment by christhompson** [comment]
Ack -- got an alert earlier this morning. Looks like the automated renewal I attempted didn't work, fix in progress.

**Comment by christhompson** [comment]
Sorry for the long downtime -- things were in a bit of a mixed up state that took some untangling to get things redeployed. The site and most endpoints should be back up and running -- there are a handful of certs I need to update with more recently renewed copies, so some certs will show up as expired (self-signed/untrusted-root and ecc256/ecc384 in particular) until I update those.

**Comment by christhompson** [comment]
This should be resolved now, so I'll close this, but let me know if you notice any lingering breakage. (`sha384`/`sha512`, `no-common-name`/`no-subject`, and the many-SANs certs are still pending getting new certs, but they're unrelated to this.)
