### ISSUE TITLE
The certificate expires

### ISSUE THREAD

**Issue by COMPUTER102** [chromium/badssl.com#518]
The certificate of https://[extended-validation.badssl.com](https://extended-validation.badssl.com/)/ expires
`颁发日期	2020年6月23日星期二 08:00:00
到期日期	2022年8月10日星期三 20:00:00`

**Comment by Karanjot786** [comment]
hello dear sir or madam i want to contribute this project. how i can start from please give me suggestion

**Comment by COMPUTER102** [comment]
> hello dear sir or madam i want to contribute this project. how i can start from please give me suggestion
@Karanjot786 You may View [this page](https://docs.github.com/zh/get-started). (However, maybe you seem to be a little off topic.)

**Comment by christhompson** [comment]
The extended validation certificate has expired and we are not planning on renewing it (due to the substantial logistics required to do so). For clarity, we should probably move it to the "defunct" section of the listings though.

**Comment by COMPUTER102** [comment]
👌Okay.
